// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/29/2026, 12:49:30 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/app/applet/frontend-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/applet/frontend-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/applet/frontend-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/applet/frontend-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/applet/frontend-nuxt/plugins/**/*.{js,ts,mjs}","/app/applet/frontend-nuxt/composables/**/*.{js,ts,mjs}","/app/applet/frontend-nuxt/utils/**/*.{js,ts,mjs}","/app/applet/frontend-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/applet/frontend-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/app/applet/frontend-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/app/applet/frontend-nuxt/app.config.{js,ts,mjs}","/app/applet/frontend-nuxt/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;